# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Area')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='City name')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoip.Area')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Country code')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Country name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='ISP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'ISP')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoip.Country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'ISP',
                'verbose_name_plural': "ISP's",
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Provider')),
                ('ranges', models.TextField(blank=True, null=True, verbose_name='Provider network ranges')),
                ('isp', models.ManyToManyField(blank=True, to='geoip.ISP', verbose_name='ISP')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='Range',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ip', models.BigIntegerField(db_index=True, verbose_name='Start range')),
                ('end_ip', models.BigIntegerField(db_index=True, verbose_name='End range')),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geoip.Area', verbose_name='Area')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geoip.City', verbose_name='City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoip.Country', verbose_name='Country')),
                ('isp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geoip.ISP', verbose_name='ISP')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='geoip.Provider', verbose_name='Provider')),
            ],
            options={
                'verbose_name': 'IP range',
                'verbose_name_plural': 'IP ranges',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoip.Country', verbose_name='Country'),
        ),
        migrations.AlterUniqueTogether(
            name='isp',
            unique_together=set([('country', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together=set([('area', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together=set([('country', 'name')]),
        ),
    ]
